project_id = "storybloom"

[api]
enabled = true
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
major_version = 15

[auth]
enabled = true
site_url = "http://localhost:8000"
additional_redirect_urls = ["http://127.0.0.1:8000"]

[auth.email]
enable_signup = true
